# This script is used to reconfigure the CPU of the server in vcenter
# we need to pass vcenter name, username, server name and how much RAM should server contains while running this script

---
- hosts: localhost
  gather_facts: false

  tasks:
  - name:  CPU upgrade
    vsphere_guest:
      vcenter_hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"        # From vault as defined
      guest: "{{ server }}"
      state: reconfigured
      validate_certs: no
      force: yes
      vm_hardware:
        num_cpus: "{{ cpu }}"
    delegate_to: localhost
